/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.LabArchivos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ashle
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    public static class Empleado {
        String Cedula;
        String Nombre;
        String Cargo;
        String Telefono;
        String FechaIngreso;
        String Salario;
        String SalarioComision;

        public Empleado(String cedula, String nombre, String cargo, String telefono, String fechaIngreso, String salario, String salarioComision) {
            this.Cedula = cedula;
            this.Nombre = nombre;
            this.Salario = salario;
            this.SalarioComision = salarioComision;
            this.FechaIngreso = fechaIngreso;
            this.Telefono = telefono;
            this.Cargo = cargo;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSortBySalary = new javax.swing.JButton();
        btnFrmAddEmpleado = new javax.swing.JButton();
        btnFrmDeleteEmpleado = new javax.swing.JButton();
        btnSortByNames = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnFrmAddVenta = new javax.swing.JButton();
        btnFrmDeleteVenta = new javax.swing.JButton();
        btnViewInforme = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/car.png"))); // NOI18N
        Bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 90, 90));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("S.A.");
        Bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Automóviles del Caribe");
        Bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/BgMenu.jpg"))); // NOI18N
        Bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 280, 500));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/favicon (1).png"))); // NOI18N
        jLabel6.setText("Automóviles del Caribe S.A.");
        Bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/empleados.png"))); // NOI18N
        jLabel3.setText("Empleados");
        Bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        btnSortBySalary.setBackground(new java.awt.Color(255, 255, 255));
        btnSortBySalary.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnSortBySalary.setForeground(new java.awt.Color(0, 0, 0));
        btnSortBySalary.setText("Ordenar Archivo por Salarios");
        btnSortBySalary.setToolTipText("Ordena el archivo de Empleados por salarios");
        btnSortBySalary.setBorder(null);
        btnSortBySalary.setBorderPainted(false);
        btnSortBySalary.setContentAreaFilled(false);
        btnSortBySalary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSortBySalary.setDefaultCapable(false);
        btnSortBySalary.setFocusPainted(false);
        btnSortBySalary.setRequestFocusEnabled(false);
        btnSortBySalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortBySalaryActionPerformed(evt);
            }
        });
        Bg.add(btnSortBySalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        btnFrmAddEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnFrmAddEmpleado.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnFrmAddEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnFrmAddEmpleado.setText("Registrar Empleado");
        btnFrmAddEmpleado.setToolTipText("Agregar un nuevo registro al archivo de empleados");
        btnFrmAddEmpleado.setBorder(null);
        btnFrmAddEmpleado.setBorderPainted(false);
        btnFrmAddEmpleado.setContentAreaFilled(false);
        btnFrmAddEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFrmAddEmpleado.setDefaultCapable(false);
        btnFrmAddEmpleado.setFocusPainted(false);
        btnFrmAddEmpleado.setRequestFocusEnabled(false);
        btnFrmAddEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrmAddEmpleadoActionPerformed(evt);
            }
        });
        Bg.add(btnFrmAddEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        btnFrmDeleteEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnFrmDeleteEmpleado.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnFrmDeleteEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnFrmDeleteEmpleado.setText("Eliminar Empleado");
        btnFrmDeleteEmpleado.setToolTipText("Eliminar un registro del archivo de empleados");
        btnFrmDeleteEmpleado.setBorder(null);
        btnFrmDeleteEmpleado.setBorderPainted(false);
        btnFrmDeleteEmpleado.setContentAreaFilled(false);
        btnFrmDeleteEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFrmDeleteEmpleado.setDefaultCapable(false);
        btnFrmDeleteEmpleado.setFocusPainted(false);
        btnFrmDeleteEmpleado.setRequestFocusEnabled(false);
        btnFrmDeleteEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrmDeleteEmpleadoActionPerformed(evt);
            }
        });
        Bg.add(btnFrmDeleteEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        btnSortByNames.setBackground(new java.awt.Color(255, 255, 255));
        btnSortByNames.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnSortByNames.setForeground(new java.awt.Color(0, 0, 0));
        btnSortByNames.setText("Ordenar Archivo por Nombres");
        btnSortByNames.setToolTipText("Ordena el archivo de Empleados por nombres");
        btnSortByNames.setBorder(null);
        btnSortByNames.setBorderPainted(false);
        btnSortByNames.setContentAreaFilled(false);
        btnSortByNames.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSortByNames.setDefaultCapable(false);
        btnSortByNames.setFocusPainted(false);
        btnSortByNames.setRequestFocusEnabled(false);
        btnSortByNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByNamesActionPerformed(evt);
            }
        });
        Bg.add(btnSortByNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/play_4043216.png"))); // NOI18N
        Bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/play_4043216.png"))); // NOI18N
        Bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/play_4043216.png"))); // NOI18N
        Bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/play_4043216.png"))); // NOI18N
        Bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/ventas.png"))); // NOI18N
        jLabel11.setText("Ventas");
        Bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        btnFrmAddVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnFrmAddVenta.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnFrmAddVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnFrmAddVenta.setText("Registrar Venta");
        btnFrmAddVenta.setToolTipText("Agregar un nuevo registro al archivo de ventas");
        btnFrmAddVenta.setBorder(null);
        btnFrmAddVenta.setBorderPainted(false);
        btnFrmAddVenta.setContentAreaFilled(false);
        btnFrmAddVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFrmAddVenta.setDefaultCapable(false);
        btnFrmAddVenta.setFocusPainted(false);
        btnFrmAddVenta.setRequestFocusEnabled(false);
        btnFrmAddVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrmAddVentaActionPerformed(evt);
            }
        });
        Bg.add(btnFrmAddVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        btnFrmDeleteVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnFrmDeleteVenta.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnFrmDeleteVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnFrmDeleteVenta.setText("Eliminar Venta");
        btnFrmDeleteVenta.setToolTipText("Eliminar un registro del archivo de ventas");
        btnFrmDeleteVenta.setBorder(null);
        btnFrmDeleteVenta.setBorderPainted(false);
        btnFrmDeleteVenta.setContentAreaFilled(false);
        btnFrmDeleteVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFrmDeleteVenta.setDefaultCapable(false);
        btnFrmDeleteVenta.setFocusPainted(false);
        btnFrmDeleteVenta.setRequestFocusEnabled(false);
        btnFrmDeleteVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrmDeleteVentaActionPerformed(evt);
            }
        });
        Bg.add(btnFrmDeleteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        btnViewInforme.setBackground(new java.awt.Color(255, 255, 255));
        btnViewInforme.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnViewInforme.setForeground(new java.awt.Color(0, 0, 0));
        btnViewInforme.setText("Relación Auto - Cantidad Vendida - Valor Total");
        btnViewInforme.setToolTipText("Muestra en pantalla una relacion entre el tipo de auto, la cantidad vendida y el valor/ganancia total");
        btnViewInforme.setBorder(null);
        btnViewInforme.setBorderPainted(false);
        btnViewInforme.setContentAreaFilled(false);
        btnViewInforme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewInforme.setDefaultCapable(false);
        btnViewInforme.setFocusPainted(false);
        btnViewInforme.setRequestFocusEnabled(false);
        btnViewInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInformeActionPerformed(evt);
            }
        });
        Bg.add(btnViewInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/play_4043216.png"))); // NOI18N
        Bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/play_4043216.png"))); // NOI18N
        Bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/play_4043216.png"))); // NOI18N
        Bg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Sistema de Gestión de Archivos  de Ventas y Empleados");
        Bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortBySalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortBySalaryActionPerformed
        try {
            File EmpleadosFile = new File("Empleados.txt");
            BufferedReader Empleados = new BufferedReader(new FileReader(EmpleadosFile));
            List<Empleado> registros = new ArrayList<>();
            String linea;
            while ((linea = Empleados.readLine()) != null) {
                String registro[] = linea.split("\t");
                Empleado empleado = new Empleado(registro[0], registro[1], registro[2], registro[3], registro[4], registro[5], registro[6]);
                registros.add(empleado);
            }
            Empleados.close();

            Collections.sort(registros, new Comparator<Empleado>() {
             @Override
                public int compare(Empleado e1, Empleado e2) {
                    double salario1 = Double.parseDouble(e1.Salario);
                    double salario2 = Double.parseDouble(e2.Salario);
                    return Double.compare(salario1, salario2);
                }
             });

            FileWriter EmpleadosSortedFile = new FileWriter("Empleados.txt", false);
            PrintWriter EmpleadosSorted = new PrintWriter(EmpleadosSortedFile);

            for (Empleado empleado : registros) {
                EmpleadosSorted.println(empleado.Cedula + "\t" + empleado.Nombre + "\t" + empleado.Cargo + "\t" + empleado.Telefono + "\t" + empleado.FechaIngreso + "\t" + empleado.Salario + "\t" + empleado.SalarioComision);
            }

            EmpleadosSorted.close();
            JOptionPane.showMessageDialog(null, "El archivo de empleados se ha ordenado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se logró ordenar el archivo de empleados", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
    }
    }//GEN-LAST:event_btnSortBySalaryActionPerformed

    private void btnSortByNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByNamesActionPerformed
        try {
            File EmpleadosFile = new File("Empleados.txt");
            BufferedReader Empleados = new BufferedReader(new FileReader(EmpleadosFile));
            List<Empleado> registros = new ArrayList<>();
            String linea;
            while ((linea = Empleados.readLine()) != null) {
                String registro[] = linea.split("\t");
                Empleado empleado = new Empleado(registro[0], registro[1], registro[2], registro[3], registro[4], registro[5], registro[6]);
                registros.add(empleado);
            }
            Empleados.close();

            Collections.sort(registros, new Comparator<Empleado>() {
                @Override
                public int compare(Empleado e1, Empleado e2) {
                    return e1.Nombre.compareTo(e2.Nombre);
                }
            });

            FileWriter EmpleadosSortedFile = new FileWriter("Empleados.txt", false);
            PrintWriter EmpleadosSorted = new PrintWriter(EmpleadosSortedFile);

            for (Empleado empleado : registros) {
                EmpleadosSorted.println(empleado.Cedula + "\t" + empleado.Nombre + "\t" + empleado.Cargo + "\t" + empleado.Telefono + "\t" + empleado.FechaIngreso + "\t" + empleado.Salario + "\t" + empleado.SalarioComision);
            }

            EmpleadosSorted.close();
            JOptionPane.showMessageDialog(null, "El archivo de empleados se ha ordenado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se logró ordenar el archivo de empleados", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
    }
    }//GEN-LAST:event_btnSortByNamesActionPerformed

    private void btnViewInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInformeActionPerformed
        ViewInforme frm = new ViewInforme();
        frm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnViewInformeActionPerformed

    private void btnFrmAddEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrmAddEmpleadoActionPerformed
        FrmAddEmpleado frm = new FrmAddEmpleado();
        frm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnFrmAddEmpleadoActionPerformed

    private void btnFrmDeleteEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrmDeleteEmpleadoActionPerformed
        FrmDeleteEmpleado frm = new FrmDeleteEmpleado();
        frm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnFrmDeleteEmpleadoActionPerformed

    private void btnFrmAddVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrmAddVentaActionPerformed
        FrmAddVenta frm = new FrmAddVenta();
        frm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnFrmAddVentaActionPerformed

    private void btnFrmDeleteVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrmDeleteVentaActionPerformed
        FrmDeleteVenta frm = new FrmDeleteVenta();
        frm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnFrmDeleteVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JButton btnFrmAddEmpleado;
    private javax.swing.JButton btnFrmAddVenta;
    private javax.swing.JButton btnFrmDeleteEmpleado;
    private javax.swing.JButton btnFrmDeleteVenta;
    private javax.swing.JButton btnSortByNames;
    private javax.swing.JButton btnSortBySalary;
    private javax.swing.JButton btnViewInforme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
